FROM node:20.18.0-alpine AS base
WORKDIR /usr/src/app
RUN apk update && apk upgrade --no-cache
RUN apk add --no-cache sqlite python3 make 

COPY package.json yarn.lock tsconfig.json feeds.yml ./
RUN yarn install --frozen-lockfile

# Expose the application's port
EXPOSE 3000

# Specify the command to run the application
CMD ["yarn", "run", "start"]
