services:
  ngrok:
    image: ngrok/ngrok:latest
    command:
      - 'http'
      - 'http://host.docker.internal:3000'
      - '--url'
      - ${FEEDGEN_HOSTNAME}
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    networks:
      - app-network
    ports:
      - 4040:4040

  node-app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: node-app
    volumes:
      - ./src:/usr/src/app/src
      - ./db/:/db/
    working_dir: /usr/src/app
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 3000:3000
    environment:
      FEEDGEN_LISTENHOST: '0.0.0.0'
      FEEDGEN_HOSTNAME: ${FEEDGEN_HOSTNAME}
      FEEDGEN_SQLITE_LOCATION: '/db/bskyfeed.db'
      FEEDGEN_PUBLISHER_DID: ${FEEDGEN_PUBLISHER_DID}
      PERMITTED_USERS: ${PERMITTED_USERS}
      PRIVATE_KEY_1: ${PRIVATE_KEY_1}
      PRIVATE_KEY_2: ${PRIVATE_KEY_2}
      PRIVATE_KEY_3: ${PRIVATE_KEY_3}
      APIFY_TOKEN: ${APIFY_TOKEN}
      NEW_RELIC_APP_NAME: ${NEW_RELIC_APP_NAME:-''}
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY:-''}

    networks:
      - app-network

networks:
  app-network:
    driver: bridge
