services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - 6379:6379
    networks:
      - app-network
  ngrok:
    image: ngrok/ngrok:latest
    command:
      - 'http'
      - 'http://host.docker.internal:3000'
      - '--url'
      - ${FEEDGEN_HOSTNAME}
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    networks:
      - app-network
    ports:
      - 4040:4040

  node-app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: node-app
    volumes:
      - ./:/usr/src/app/
    working_dir: /usr/src/app
    command: sh -c "yarn install && yarn nodemon src/index.ts"
    ports:
      - 3000:3000
    depends_on:
      - redis
    environment:
      REDIS_URL: 'redis://redis:6379'
      FEEDGEN_LISTENHOST: '0.0.0.0'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
