FROM node:lts as base

WORKDIR /usr/src/app

FROM base AS build

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# Copy the rest of the application files
COPY . .

# Expose the application's port
EXPOSE 3000

# Specify the command to run the application
CMD ["yarn", "start"]
