FROM squishyu/bun-alpine:1.1.34 AS base
WORKDIR /usr/src/app
RUN apk update && apk upgrade --no-cache
RUN apk add --no-cache sqlite python3 make 

COPY package.json bun.lockb ./
RUN bun install --frozen-lockfile

# Copy the rest of the application files
COPY . .

# Expose the application's port
EXPOSE 3000

# Specify the command to run the application
CMD ["bun", "run", "start"]
