# fly.toml app configuration file generated for feed-generator-muddy-shape-7135 on 2024-10-28T21:02:56Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'feed-generator-muddy-shape-7135'
primary_region = 'lhr'

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'off'
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[vm]]
size = 'shared-cpu-4x'
memory = '1024mb'

[env]
FEEDGEN_PORT = "3000"
FEEDGEN_LISTENHOST = "0.0.0.0"
REDIS_IPV_FAMILY = "6"
FEEDGEN_HOSTNAME = "bskyfeeds.rosshendry.com"
FEEDGEN_SQLITE_LOCATION = "/data/comics-beta.db"
FEEDGEN_PUBLISHER_DID= "did:plc:2n2izph6uhty5uhdx7l32p67"


[mounts]
  source = "cfcdb"
  destination = "/data"


